export const DEBATE_CONFIG = {
  REQUIRED_EXPERTS: 4,
  TOTAL_TURNS: 12,
  MAX_RETRIES: 3,
  TIMEOUT_MS: 115_000,
  RETRY_STREAM_DELAY_MS: 2000,
  RETRY_ERROR_DELAY_MS: 3000,
  NEXT_TURN_DELAY_MS: 1500,
  START_DEBATE_DELAY_MS: 1000,
} as const;

export const STORAGE_KEYS = {
  CUSTOM_BRANCHES: 'customBranches',
} as const;
